# Based on https://github.com/JuliaDiff/ChainRulesCore.jl/tree/caf8692ca1bf5fabeb4afc86340eef9456da469c
name: IntegrationTest
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: ${{ matrix.package.repo }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: [1.6]
        os: [ubuntu-latest]
        package:
          - {user: Ferrite-FEM, repo: FerriteDistributed.jl}
          - {user: Ferrite-FEM, repo: FerriteGmsh.jl}
          - {user: Ferrite-FEM, repo: FerriteMeshParser.jl}
          - {user: Ferrite-FEM, repo: FerriteViz.jl}

    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v1
      - name: Clone Downstream
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.package.user }}/${{ matrix.package.repo }}
          path: downstream
      - name: Load this and run the downstream tests
        shell: julia --project=downstream {0}
        run: |
          using Pkg
          try
            # force it to use this PR's version of the package
            Pkg.develop(PackageSpec(path="."))  # resolver may fail with main deps
            Pkg.update()
            Pkg.test()  # resolver may fail with test time deps 
          catch err
            err isa Pkg.Resolve.ResolverError || rethrow()
            # If we can't resolve that means this is incompatible by SemVer and this is fine
            # It means we marked this as a breaking change, so we don't need to worry about
            # Mistakenly introducing a breaking change, as we have intentionally made one

            @info "Not compatible with this release. No problem." exception=err
            exit(0)  # Exit immediately, as a success
          end
